name: My First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Welcome to Github Actions"
            
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: List of files
              run: ls -altr

            - name: Read File
              run: cat README.md