name: Run Multiple jobs
on: push
jobs:
    build_job_1:
      runs-on: ubuntu-latest
      steps:
      - name: Download Cowsay application
        run: sudo apt-get install cowsay
      - name: Execute cowsay dragon
        run: cowsay -f dragon "This is dragon, national animal of china !!!!" >> dragon.txt
        
      - name: Upload dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
  
    test_job_2:
      needs: build_job_1
      runs-on: ubuntu-latest
      steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Check for Dragon
        run: grep -i "dragon" dragon.txt
  
    deploy_job_3:
      needs: test_job_2
      runs-on: ubuntu-latest
      steps:
      - name: Download dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

      - name: Read the Dragon file
        run: cat dragon.txt
        
      - name: Deploy dragon file
        run: echo "Deploy dragon file"