name: Variable and secrets usage
on: push
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USER: adoptnext
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: adnext-nginx
    steps:
      - name: Docker Build
        run: echo docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:latest

      - name: Docker Login
        env:
          DOCKER_PASSWORD: dek39djdlow
        run: echo docker login --username $DOCKER_USER --password=$DOCKER_PASSWORD

      - name: Docker Push
        run: echo docker push $DOCKER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: adnext-nginx
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.DOCKER_REGISTRY }}/$DOCKER_USER/$IMAGE_NAME:latest
